# Generated by Django 3.2.5 on 2021-07-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20210705_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='painting_cover_pictures'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='clothing_cover_pictures'),
        ),
        migrations.AlterField(
            model_name='laptop_cover',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='laptop_cover_pictures'),
        ),
        migrations.AlterField(
            model_name='mobile_cover',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='mobile_cover_pictures'),
        ),
    ]
